### ISSUE TITLE
崩溃BUG一份，请注意查收，版本1.2.17build537

### ISSUE THREAD

**Issue by YXG1994** [Ccixyj/JBusDriver#72]
尝试过清除数据，依然无效，期待修复

#######RuntimeEnvironmentInformation#######
crash time=2019-03-23 10:45:11.944
model=SM-N9100
android version=4.4.4(19)
brand=samsung
manufacturer=samsung
board=APQ8084
hardware=qcom
device=trltechn
version name=1.2.17build537
cpu_abi=armeabi-v7a
cpu_abi2=armeabi
display=KTU84P.N9100ZCU1AOB1
#######ForceCloseCrashLog#######
FATAL EXCEPTION: main
Process: me.jbusdriver, PID: 27580
java.lang.ExceptionInInitializerError
	at okhttp3.ad.a(OkHttpClient.java:263)
	at okhttp3.ad.<init>(OkHttpClient.java:229)
	at okhttp3.ad$a.a(OkHttpClient.java:1015)
	at me.jbusdriver.base.c.a$e.a(NetClient.kt:111)
	at me.jbusdriver.base.c.a$e.invoke(NetClient.kt:22)
	at b.n.a(LazyJVM.kt:74)
	at me.jbusdriver.base.c.a.e(NetClient.kt)
	at me.jbusdriver.base.c.a.a(NetClient.kt:81)
	at me.jbusdriver.a.a$a$a.a(GitHub.kt:23)
	at me.jbusdriver.a.a$a$a.invoke(GitHub.kt:22)
	at b.n.a(LazyJVM.kt:74)
	at me.jbusdriver.a.a$a.a(GitHub.kt)
	at me.jbusdriver.ui.activity.SplashActivity.k(SplashActivity.kt:75)
	at me.jbusdriv

**Comment by YXG1994** [comment]
要是无法修复，或者说是某些功能安卓 4.4无法支持，那么我得去哪下载上一个版本啊？期待大佬的回复，谢谢

**Comment by Ccixyj** [comment]
这个问题只在4.4复现，你可以使用5.x以上的android手机
